// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
)

type Post struct {
	ID        int32          `json:"id"`
	Title     sql.NullString `json:"title"`
	Link      sql.NullString `json:"link"`
	Img       string         `json:"img"`
	Content   string         `json:"content"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
